[project]
name = "basket-optimizer"
version = "0.1.0"
description = "PaketAI case study ðŸ‘¨â€ðŸ³"
authors = [{ name = "orhantugrul", email = "orhantugrulsahin@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopy>=2.4.1",
    "ortools>=9.10.0",
    "pydantic>=2.12.4",
    "sanic-cors>=2.2.0",
    "sanic[ext]>=25.3.0",
    "scipy>=1.11.0",
    "shapely>=2.1.2",
]

[dependency-groups]
dev = [
    "commitizen>=4.10.0",
    "pre-commit>=4.4.0",
    "pytest>=9.0.1",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.14.4",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
